# Generated by Django 5.0.7 on 2024-07-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name_plural": "movies"},
        ),
    ]
